"""empty message

Revision ID: 72a227e6814e
Revises: 77a8cbb45440
Create Date: 2025-10-28 21:17:12.060953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72a227e6814e'
down_revision = '77a8cbb45440'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_pages', sa.Integer(), nullable=False))
        batch_op.drop_column('count_pages')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count_pages', sa.INTEGER(), nullable=False))
        batch_op.drop_column('total_pages')

    # ### end Alembic commands ###
