"""empty message

Revision ID: d1c63c5cd39f
Revises: 74495668af1c
Create Date: 2025-10-31 22:32:01.392269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1c63c5cd39f'
down_revision = '74495668af1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('bootstrap_color', sa.Enum('PRIMARY', 'SECONDARY', 'SUCCESS', 'DANGER', 'WARNING', 'INFO', 'LIGHT', 'DARK', name='bootstrapcolor'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('name', name=op.f('uq_tags_name'))
    )
    op.create_table('books_tags',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_books_tags_book_id'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_books_tags_tag_id'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_id', 'tag_id', name=op.f('pk_books_tags'))
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publication_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('isbn', sa.String(), nullable=True))
        batch_op.alter_column('total_pages',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_books_author_id'), ['author_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_books_author_id'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_books_author_id'), 'authors', ['author_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_books_author_id'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_books_author_id'), 'authors', ['author_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_books_author_id'))
        batch_op.alter_column('author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('total_pages',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('isbn')
        batch_op.drop_column('publication_date')

    op.drop_table('books_tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
